### ISSUE TITLE
Spot the differences with the Diamond policy

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISDataPolicy/policy#10]
Suggested by Steve Collins (Diamond). 

Current Diamond policy https://www.diamond.ac.uk/Users/Policy-Documents/Policies/Experimental-Data-Management-Pol.html . 

However a new Diamond policy is expected (Steve), and hence probably make more sense to spot the difference with the new policy.

Until then this issue is a reminder to look into this.

**Comment by srconway** [comment]
https://www.diamond.ac.uk/Home/Legal-and-Compliance/Policies/Experimental-Data-Management-Pol.html seems to be the current link

**Comment by martyngigg** [comment]
I met with Steve Collins from Diamond regarding the new Diamond policy. I'll summarize the key points in the review meeting on 25/01/24.

**Comment by martyngigg** [comment]
- DOIs will be minted ~1 week after expt as a fixed snapshot of experiment.
- Suggestion that PI makes data open after 3 years but the PI has responsibility to make this happen.
  - No need for embargo period.
  - A lot of sensitivity around a lot of data.
  - Make PI driver of OPEN data.
  - Diamond provides tools to make it happen.
- Tools to create separate, user-defined DOIs for curated packages of data.

**Comment by martyngigg** [comment]
Steve gave an update on this at the meeting on 22/02/2024.
