### ISSUE TITLE
Suggested minor text change in 2.7 - web-based browsers

### ISSUE THREAD

**Issue by agbeltran** [ISISDataPolicy/policy#11]
In 2.7, it reads 

"2.7 The term ‘on-line catalogue’ pertains to a computer database of metadata containing links to raw data files, that can be accessed by a variety of methods, including (but not limited to) www-based browsers."

I suggest to change "www-based browsers" to "web-based browsers".

**Comment by Anders-Markvardsen** [comment]
`web-based` reads better to me also and thanks for the issue
