### ISSUE TITLE
Use "proprietary user" instead of "commercial user"?

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISDataPolicy/policy#15]
Concerning `...owned exclusively by the commercial user`.

Elsewhere "commercial data" been replaced by "proprietary data" to be more explicit about type of data.

Same swap for user?

**Comment by srconway** [comment]
Can we also clarify whether we're talking about a company or an individual? If the PI moves to a new job, does the data belong to them or to the organisation that was employing them at the time of the experiment (and who presumably paid for it)

There may be a similar issue for non-commercial PIs moving between institutions but it's probably more of an issue with commercial ones. Currently the data is accessibile the PI and co-Is and we ought to clarify what we do if someone else from the same organisation asks for access, or asks to have the PI's access revoked.
