### ISSUE TITLE
Create a "share" or "functional" account for linking to Zenodo

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISDataPolicy/policy#16]
At this time, Anders' github account links to the automated process for creating new DOIs with each new release of this repo. This causes the problem that Anders is the only person who can subsequently edit metadata of these automatically created DOIs. 

Change this, before the next release, such that automated created DOIs are created from a "shared" or "functional" account

**Comment by martyngigg** [comment]
I've created a "bot" GitHub account called [isisdatapolicybot](https://github.com/isisdatapolicybot/). I need to sit with Anders and switch the Zenodo linking to this new account.

I've set up a separate meeting (29/04/2024) with Anders to sort this out.

**Comment by martyngigg** [comment]
This has now been switched over and Zenodo has been linked to the [isisdatapolicybot](https://github.com/isisdatapolicybot) account. The details are in my Keeper account and can be shared.
