### ISSUE TITLE
Clarify public metadata elements

### ISSUE THREAD

**Issue by agbeltran** [ISISDataPolicy/policy#18]
Section 3.4.3 refers to some metadata elements being public, as clarified in the proposals system:

"3.4.3 During the proposals process, some elements of the metadata associated with an experiment (such as the title) are indicated as being public"

It would be good if the policy included more details about those elements, and perhaps a link to where all the elements are listed.

**Comment by WHTaylor** [comment]
Additionally, does/should this apply to commercial experiments?

**Comment by martyngigg** [comment]
- Clarify 3.4.3 relates to DOI minting.
