### ISSUE TITLE
Data Ownership

### ISSUE THREAD

**Issue by shodder** [ISISDataPolicy/policy#19]
Some topics to discuss around data ownership:
- Who owns the data produced at STFC (us, the researcher, the university)
- If a researcher moves to a different university, do we need to update access permissions to data?
- For commercial data, what happens if someone moves jobs? 
- How can we know any of the above unless we are informed?

**Comment by WHTaylor** [comment]
Current:

4.1 Ownership of result data

4.1.1 Ownership of all result data derived from users manually reducing raw data and analysing raw data, or both, is determined by the contractual obligations of the person(s) performing the analysis.

**Comment by martyngigg** [comment]
This has come up in the file format comment mentioned in #18. Reduced data formats are now wanting to capture things like raw data ownership information. As Simon says, the ownership of the non-proprietary access is not clear in the policy - who does own it in this case?

**Comment by martyngigg** [comment]
This was discussed in relation to the non-proprietary data. Abigail pointed out that as part of the ExPaNDS project, [guidelines](https://zenodo.org/records/6090282/files/ExPaNDS-Guidance-Note-Data-Policy-Framework-revised.pdf?download=1) were developed for those writing data policies. Their conclusion is that ownership is a complex issue with different arrangements & legal implications across countries and institutions and should be left to contracts between institutions and their users. It is up to institutions and users to handle issues such as researchers moving institutions and notifying facilities.
