### ISSUE TITLE
Clarify 'indefinite' data retention for DOIs

### ISSUE THREAD

**Issue by srconway** [ISISDataPolicy/policy#20]
See https://github.com/isisbusapps/ISISBusApps/issues/827 for details. What are we keeping indefinitely, including personal details, and is it correctly documented in the policy?

(Note #827 is just a reference to item ID4 from the [Deloitte task list](https://stfc365.sharepoint.com/:x:/r/sites/isiscomputingdivision-staffsite/Shared%20Documents/Bus%20Apps%20Systems/Deloitte%20task%20list.xlsx?d=wc6c985b64aaa4d0faa355eb3fb5a982e&csf=1&web=1&e=ajul6W).)

**Comment by Anders-Markvardsen** [comment]
@srconway the link above does not work for me

**Comment by srconway** [comment]
@Anders-Markvardsen can you access the deloitte list - the issue is purely a reference to that.

**Comment by Anders-Markvardsen** [comment]
@srconway can see the deloitte list 👍 . 'Indefinitely' is not defined in the data policy. The closest being `2.9 The term ‘long-term’ means a minimum of ten years.`
