### ISSUE TITLE
Ensure IDAaaS complies with data policy

### ISSUE THREAD

**Issue by srconway** [ISISDataPolicy/policy#21]
This is work in progress - by removing the ISIS data archive link we ensure compliance. There are side issues around how we capture data in IBEX/SECI as incorrect data capture could lead to us inadvertently exposing data, or blocking it from valid users.

Just adding this issue to track progress

**Comment by srconway** [comment]
re IBEX/SECI the policy states:
>  3.6.3 It is the responsibility of the PI to ensure that the experiment number (RB number) is correctly entered into the metadata for each raw data set, in order to correctly associate each data set with the PI. If this is not done, the experimental team may not be able to access the data via the on-line catalogue and any facility-provided computing infrastructure, and other users may inadvertently be given access rights to the data.

**Comment by martyngigg** [comment]
Our hope is that by the next ISIS cycle (starts 13th Feb 2024) the archive will be, by default, disconnected for IDAaaS workspaces. Federal IDs will be required to reactivate the link.

**Comment by martyngigg** [comment]
This was in place from cycle 23/5 (Feb 2024) with help from the DAaaS team.
