### ISSUE TITLE
Connections between proposals and embargoed data

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISDataPolicy/policy#9]
What is the connections between proposals and embargoed data? 

Understand of this is currently, and reconsider who we refer to proposal in the policy.

One place where we do this currently is

- 3.6.5 The on-line catalogue will enable the linking of experimental data to experimental proposals. Access to proposals will only ever be provided to the experimental team and appropriate STFC staff, unless otherwise authorized by the PI (with the exception of those parts of the online proposal which are flagged as publicly accessible within the proposal system).

**Comment by WHTaylor** [comment]
Currently:
 - The proposal PDF, which has detailed plans for the experiment, is only accessible for the experiment team.
 - Some proposal metadata (the title, abstract, and experimenter names) is included in DOIs which are created and publically accessible during the embargo period.

The current 3.6.5 probably refers to the proposal PDFs, but this should be clarified.

If the other metadata is relevant to the policy (which it probably is), how we handle it should be included as either an extension to 3.6.5, or as a separate point.
